### ISSUE TITLE
Not compiling under clang 12

### ISSUE THREAD

**Issue by DoktorBotti** [TooBiased/growt#6]
Unfortunately, the project does not compile due to some constexpr violations for the _mapper type in base_linear.hpp as seen below:
```
/home/user/build/project/libs/growt/./data-structures/base_linear.hpp:1160:19: error: constexpr if condition is not a constant expression
    if constexpr (_mapper.cyclic_mapping)
                  ^~~~~~~~~~~~~~~~~~~~~~
```
I got this behavior for both clang 12 and 10.

**Comment by TooBiased** [comment]
I just committed a fix. Please notify me, if you are still encountering any errors.

It looks like there are a lot of compiler warnings, when using clang, maybe I will fix these at some point, but I would not expect this before late summer.
