### ISSUE TITLE
TBB is a Prerequisite to include table_config.hpp

### ISSUE THREAD

**Issue by xanderdunn** [TooBiased/growt#7]
The README indicates that grow can be used all on its own without any third part libraries.  However, data-structures/table_config.hpp includes data-structures/element_types/complex_slot.hpp, which includes tbb/scalable_allocator.h. TBB must be installed to use growt's hash map.

**Comment by TooBiased** [comment]
Done. The default allocator is now std::allocator. TBB can be reactivated via #define TBB_AS_DEFAULT.
