### ISSUE TITLE
utils/hash/murmur3_hash.hpp includes non-existent MurmurHash3.cpp

### ISSUE THREAD

**Issue by xanderdunn** [TooBiased/growt#8]
utils/hash/murmur3_hash.hpp has a line `#include "MurmurHash3.cpp"`, but the compiler can't find this file, and I don't see it in the [utils repo either](https://github.com/TooBiased/utils_tm/tree/61d423b53a755f03385f6469af000bfb16a6175f/hash).

**Comment by TooBiased** [comment]
Yes, the source code for MurmurHash3 is in the smhasher library, I just wrote a wrapper in my utils library. To compile with MurmurHash3 you have to add an appropriate include path

**Comment by TooBiased** [comment]
I just added smhasher as another submodule and added some code to the cmake file, which makes it a little more clear how to use it.
